### PR TITLE
build: nix

### PR DESCRIPTION
**Pull request by Guekka**

### CODE REVIEW

**Review by low-hik — CHANGES_REQUESTED** [review]
please put that in your gitignore

**Review by low-hik — DISMISSED** [review]
please put that in your gitignore

**Comment by Guekka** [comment]
(that was a joke)

**Review by ozeliurs — APPROVED** [review]
Please put that in your gitignore

**Review by low-hik — CHANGES_REQUESTED** [review]
where is the associated issue ?

**Pull request merged**
