### PR TITLE
20 restaurant page

### LINKED ISSUE #20: Restaurant Page
IHM12  2

IHM13

### PR DESCRIPTION
**Pull request by ozeliurs**

### CODE REVIEW

**Review by Guekka — CHANGES_REQUESTED** [review]
When I select "list", the "location" button is still highlighted in the navbar

Also, I can't go back to the list once I select a restaurant

**Comment by ozeliurs** [comment]
@Guekka Cannot recreate the first bug and fixed back button at https://github.com/KFC-IHM/Restorater/pull/27/commits/826f346c38e6bae4d8eb549c3a2abb5afb6747cb .

**Comment by Guekka** [comment]
@ozeliurs Beware of force pushes. You erased my changes. It's not important, I can restore it, but use `force-with-lease`

**Review by Guekka — CHANGES_REQUESTED** [review]
Now I can't access the location tab

**Comment by ozeliurs** [comment]
@Guekka You cannot access location because location is not in this branch

**Review by Guekka — DISMISSED** [review]
lgtm

**Pull request merged**
